server:
  port: 8082
  servlet:
    context-path: /api/v1/private/
spring:
  application:
    name: redis-demo

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=redis
    username: postgres
    password: 123456

  flyway:
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379

